apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: first-microservice
  name: first-microservice
  namespace: micro-service
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    k8s-app: first-microservice
